"""
Script to generate sample outputs for demonstration.

This script creates sample query-response pairs and saves them
as JSON files in the examples/sample_outputs directory.
"""

import json
import os
from pathlib import Path

# Create sample outputs directory
output_dir = Path("examples/sample_outputs")
output_dir.mkdir(parents=True, exist_ok=True)

# Sample outputs (these would normally be generated by running the system)
sample_outputs = [
    {
        "query": "How do I create a list in Python?",
        "answer": "You can create a list in Python using square brackets. Here are several ways:\n\n```python\n# Empty list\nmy_list = []\n\n# List with items\nmy_list = [1, 2, 3]\n\n# List with mixed types\nmy_list = ['apple', 42, True]\n```\n\nLists are mutable, meaning you can modify them after creation.",
        "sources": [
            {
                "title": "Data Structures",
                "source_url": "https://docs.python.org/3/tutorial/datastructures.html",
                "score": 0.95,
                "text": "Python lists are created using square brackets..."
            }
        ],
        "response_time": 2.1,
        "num_sources": 1
    },
    {
        "query": "Explain Python decorators with an example",
        "answer": "Python decorators are a way to modify or extend the behavior of functions without permanently modifying them. They use the @ symbol syntax.\n\n```python\ndef my_decorator(func):\n    def wrapper():\n        print(\"Something before the function\")\n        func()\n        print(\"Something after the function\")\n    return wrapper\n\n@my_decorator\ndef say_hello():\n    print(\"Hello!\")\n\nsay_hello()\n```\n\nDecorators are essentially functions that take other functions as arguments.",
        "sources": [
            {
                "title": "More on Defining Functions",
                "source_url": "https://docs.python.org/3/tutorial/controlflow.html#more-on-defining-functions",
                "score": 0.89,
                "text": "Python decorators allow you to modify functions..."
            }
        ],
        "response_time": 3.5,
        "num_sources": 1
    },
    {
        "query": "What are Python data types?",
        "answer": "Python has several built-in data types:\n\n1. **Numbers**: int, float, complex\n2. **Sequences**: list, tuple, str, bytes\n3. **Mappings**: dict\n4. **Sets**: set, frozenset\n5. **Booleans**: bool\n6. **None**: NoneType\n\nEach type has specific characteristics and use cases.",
        "sources": [
            {
                "title": "Data Structures",
                "source_url": "https://docs.python.org/3/tutorial/datastructures.html",
                "score": 0.91,
                "text": "Python has several built-in data types..."
            }
        ],
        "response_time": 2.8,
        "num_sources": 1
    },
    {
        "query": "How do I handle exceptions in Python?",
        "answer": "You handle exceptions in Python using try-except blocks:\n\n```python\ntry:\n    # Code that might raise an exception\n    result = 10 / 0\nexcept ZeroDivisionError:\n    # Handle the exception\n    print(\"Cannot divide by zero\")\nexcept Exception as e:\n    # Handle other exceptions\n    print(f\"An error occurred: {e}\")\nfinally:\n    # Code that always runs\n    print(\"Cleanup code\")\n```",
        "sources": [
            {
                "title": "Errors and Exceptions",
                "source_url": "https://docs.python.org/3/tutorial/errors.html",
                "score": 0.93,
                "text": "Python uses try-except blocks for exception handling..."
            }
        ],
        "response_time": 2.5,
        "num_sources": 1
    },
    {
        "query": "What is the difference between a tuple and a list?",
        "answer": "The main differences between tuples and lists in Python are:\n\n1. **Mutability**: Lists are mutable (can be changed), tuples are immutable (cannot be changed)\n2. **Syntax**: Lists use square brackets `[]`, tuples use parentheses `()`\n3. **Performance**: Tuples are slightly faster and use less memory\n4. **Use cases**: Lists for collections that change, tuples for fixed collections\n\n```python\n# List (mutable)\nmy_list = [1, 2, 3]\nmy_list.append(4)  # OK\n\n# Tuple (immutable)\nmy_tuple = (1, 2, 3)\n# my_tuple.append(4)  # Error!\n```",
        "sources": [
            {
                "title": "Data Structures - Tuples",
                "source_url": "https://docs.python.org/3/tutorial/datastructures.html#tuples-and-sequences",
                "score": 0.87,
                "text": "Tuples are immutable sequences..."
            }
        ],
        "response_time": 3.2,
        "num_sources": 1
    }
]

# Save individual files
for i, output in enumerate(sample_outputs, 1):
    filename = f"query_{i:02d}.json"
    filepath = output_dir / filename
    
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(output, f, indent=2, ensure_ascii=False)
    
    print(f"Saved: {filepath}")

# Save combined file
combined_file = output_dir / "all_outputs.json"
with open(combined_file, 'w', encoding='utf-8') as f:
    json.dump(sample_outputs, f, indent=2, ensure_ascii=False)

print(f"\n✅ Generated {len(sample_outputs)} sample outputs")
print(f"📁 Output directory: {output_dir}")

